language: java
sudo: false
jdk:
- openjdk8
branches:
  only:
  - master
  - develop
  - master-nbn
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.m2/wrapper"
before_install:
- export TZ=Europe/London
- date
- mkdir -p ~/.m2
- wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/nbnuk/travis-build-configuration/master/travis_maven_settings.xml
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./mvnw -B deploy -DskipTests=true'
env:
  global:
  - secure: BW4FswyT+ZB8351SQnUbrCMGr3PCFRL4TbueAcdzFZMy4t0RoDrD6zEC/EUjBtKz2tiijYXDGqyoCRtHs+zStBVMLjriraVqPED2a9PnbCIyQpRn7fp/wdlzqPWcgM/nFj+yQyKkR3i+GpWNRViPO2kqdOmbF2agcD9Fzf0rOQflkhT8b9YcZUVhNZ9UUsYrAoWs2Sf8cvVkEJG3aqCLOpGrIs+dfr2u5cAyvi6ScsWPcb2Go46zaEsAld2gGPbKuSnAAjpxk1F1Bfg0cfWk2B21N7Pz7/h6sPj8Fe14hSQ1rWCtvFaR2+wM3fU31y91z+U4MzgTpdzTJ++UhvFQuawcjXzVurFfLeazHVAljzlnZXeT3cxU157Dxr8PcR/gg04Wm3nurwtMpc4anXwuudFTromhnbpsuBg0WXAarEiB1U2dBjO4JfFGL486QjN6Ppd3olMXLISmQe+x2f7QyYmVq/iZcb4pQ5SLY44YtdS6woEztK6Z1OcxILrhYRyfhbSKL52HCBJOGAvGFdrVDObU2qMGwRhlCa3gFXtg408b7BkiaK1zMtDQ8SGivigztuHk3seLASECVmuqECtLA3onS02qIJ3gFdJWZgzqVrvRxaA89bB2b4SKPLADuftMNa5pVl12+gT+BKw7rlCvwnrBn5cWbjtazcdCG3jsAYY=
  - secure: kFWlqoeFuUUl/yNXBuewP20nLYRsuj5/fDEW+ERoL4mJiZcdJDT6aEnQfFVjVX1rnjl794Cy57a9SXhUaYLg+0nJIomXQArNgKMn7UeoCk9/+tQRjyL0xGQxfabqjXaemRE09ICGKXVGpq58kdyD2KlVH6memjlw8c47lm4J8RKLxzq0xmJ/mMlapUa38mIrTs/kVj29MsRJ0oZf9vABciDuZUvB73CDHjrry6ckEY7zNDxVa5HBROstWRPFVq1bJNUT/dVUx6ckxwE2JlBucbap3oxfbeg/mx2lRiVgScKoNddhOiYtKmls8ZBCk6cRygV0kQOlFQOW0AQBQPln4kDEpaKhXNzmz3CPd5KRnEATdOw8sPKGYoJFRWnz25NqHiP02u9RYhfqQF85fc38snHvsctamTbeMLR5NtO2iypn7r1fAvUotKjVJt7pVENSXyDLR9y8WWcbAtQAAeO2rzgKGQ7WlXZfS6ULNdifkW7qc50smwdn7i5BdTC5WuAp00lT6rQ1XUjvUGpU6fKaei+rrr7AitZnNXktVWyGFmILLckctHEXtcAx7Po4Afajx8IaFbaGd7fpKJr01B/xEyrQPABu8g+5vdobYHXqefnEnDtyei5Ua7fxdCid/0iixdjqvgqw62LUCzfpjysDmIytwkLIijjR7N5qYnk+EDU=
